// pages/home/home.js
Page({
  data: {
    cardCur: 0,
    swiperList: [{
      id: 0,
      type: 'image',
      url: '../../../images/guide.png',
    }, {
      id: 1,
      type: 'image',
      url: '../../../images/announce.png'
    }],
    medicineImgList: [{
      id: 0,
      type: 'image',
      name:"respiratory",
      title:"呼吸",
      url: '../../../icons/homeIco/huxi.png'
    }, {
      id: 1,
      type: 'image',
        name: "cardiovascular",
      title: "心血管",
      url: '../../../icons/homeIco/xinzang.png',
      }, {
        id: 2,
        type: 'image',
        name: "digestion",
        title: "消化",
        url: '../../../icons/homeIco/xiaohua.png',
      }, {
        id: 3,
        type: 'image',
        name: "kidney",
        title: "泌尿",
        url: '../../../icons/homeIco/shen.png',
      }, {
        id: 4,
        type: 'image',
        name: "haematic",
        title: "血液",
        url: '../../../icons/homeIco/xieguan.png',
      }, {
        id: 5,
        type: 'image',
        name: "endocrine",
        title: "内分泌",
        url: '../../../icons/homeIco/neifenmi.png',
      }],

    // 外科索引
    surgeryImgList: [{
      id: 0,
      type: 'image',
      name: "general",
      title: "总论",
      url: '../../../icons/homeIco/waike.png'
    }, {
      id: 1,
      type: 'image',
      name: "brain",
      title: "头部",
      url: '../../../icons/homeIco/tou.png',
    }, {
      id: 2,
      type: 'image',
      name: "gland",
      title: "两腺",
      url: '../../../icons/homeIco/jiazhuangxian.png',
    }, {
      id: 3,
      type: 'image',
      name: "chest",
      title: "胸部",
      url: '../../../icons/homeIco/xiongbu.png',
    }, {
      id: 4,
      type: 'image',
      name: "abdomen",
      title: "腹部",
      url: '../../../icons/homeIco/fubu.png',
    }, {
      id: 5,
      type: 'image',
      name: "liver",
      title: "肝胆胰",
      url: '../../../icons/homeIco/gan.png',
      }, {
        id: 6,
        type: 'image',
        name: "rectal",
        title: "直肠",
        url: '../../../icons/homeIco/gang.png',
      }, {
        id: 7,
        type: 'image',
        name: "urinary",
        title: "泌尿",
        url: '../../../icons/homeIco/shen.png',
      }, {
        id: 8,
        type: 'image',
        name: "vessel",
        title: "血管",
        url: '../../../icons/homeIco/xieguan.png',
      }, {
        id: 9,
        type: 'image',
        name: "orthopedics",
        title: "骨科",
        url: '../../../icons/homeIco/gu.png',
      }
    ],
    OGImgList: [{
      id: 0,
      type: 'image',
      name: "generalOG",
      title: "总论",
      url: '../../../icons/homeIco/funv.png'
    }, {
        id: 1,
        type: 'image',
        name: "gynecology",
        title: "产科",
        url: '../../../icons/homeIco/renshen.png'
      }, {
        id: 2,
        type: 'image',
        name: "obstetrics",
        title: "妇科",
        url: '../../../icons/homeIco/fuke.png'
      }, 
    ],

    // 儿科各类
    pediatricsImgList: [{
      id: 0,
      type: 'image',
      name: "generalP",
      title: "绪论",
      url: '../../../icons/homeIco/ertong.png'
    }, {
      id: 1,
      type: 'image',
      name: "nutrition",
      title: "营养",
      url: '../../../icons/homeIco/yingyang.png'
    }, {
      id: 2,
      type: 'image',
      name: "neonatal",
      title: "新生儿",
      url: '../../../icons/homeIco/yuer.png'
      }, {
        id: 3,
        type: 'image',
        name: "inheritance",
        title: "遗传",
        url: '../../../icons/homeIco/jiyin.png'
      }, {
        id: 4,
        type: 'image',
        name: "immunization",
        title: "免疫",
        url: '../../../icons/homeIco/mianyi.png'
      }, {
        id: 5,
        type: 'image',
        name: "infection",
        title: "感染",
        url: '../../../icons/homeIco/chuanran.png'
      }, {
        id: 6,
        type: 'image',
        name: "digestionP",
        title: "消化",
        url: '../../../icons/homeIco/xiaohua.png'
      }, {
        id: 7,
        type: 'image',
        name: "respiratoryP",
        title: "呼吸",
        url: '../../../icons/homeIco/huxi.png'
      }, {
        id: 8,
        type: 'image',
        name: "cardiovascularP",
        title: "心血管",
        url: '../../../icons/homeIco/xinzang.png'
      }, {
        id: 9,
        type: 'image',
        name: "urinaryP",
        title: "泌尿",
        url: '../../../icons/homeIco/shen.png'
      }, {
        id: 10,
        type: 'image',
        name: "haematicP",
        title: "血液",
        url: '../../../icons/homeIco/xieguan.png'
      }, {
        id: 11,
        type: 'image',
        name: "neural",
        title: "神经",
        url: '../../../icons/homeIco/shenjing.png'
      }, {
        id: 12,
        type: 'image',
        name: "endocrineP",
        title: "内分泌",
        url: '../../../icons/homeIco/neifenmi.png'
      },
    ]
  }
})